# SonarQube Project Configuration
sonar.projectKey=roshankumar0036singh_Uni-Event
sonar.projectName=Uni-Event
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=app,cloud-functions/src

# Path to test directories
sonar.tests=tests

# Exclusions from source analysis
sonar.exclusions=node_modules/**,app/node_modules/**,cloud-functions/node_modules/**,cloud-functions/lib/**,dist/**,build/**,coverage/**,scratch/**,**/*.spec.js,**/*.test.js


# Source encoding
sonar.sourceEncoding=UTF-8

# JavaScript / TypeScript Configuration
sonar.javascript.environments=browser,node
